export const expenseClaimsList = [
  {
    id: 1,
    name: 'Thanh toán lần 1 Hợp đồng số AAV/2021/CS/PROG/17',
    date: '28/12/2021',
    claimant: 'Vũ Thị Huyền Sâm',
    department: 'Operations',
    organization: 'AAV',
    type: 'Fund transfer request',
    claimedAmount: '910,041,000 VND',
    status: 'Approved',
  },
  {
    id: 2,
    name: 'Chi phi kiem toan du an CFK Ngo Quyen',
    date: '28/12/2021',
    claimant: 'Phạm Khánh Toàn',
    department: 'Operations',
    organization: 'AFV',
    type: 'Fund transfer request',
    claimedAmount: '30,000,000 VND',
    status: 'Inprogress',
  },
  {
    id: 3,
    name: 'Giải thưởng cho tác giả đoạt giả cuộc thi "Những cống hiến thầm lặng"',
    date: '28/12/2021',
    claimant: 'Lê Phương Thảo',
    department: 'Programme',
    organization: 'AAV',
    type: 'Expense claim',
    claimedAmount: '108,000,000 VND',
    status: 'Approved',
  },
  {
    id: 4,
    name: 'Chi phi kiem toan du an CFK Binh Tan',
    date: '28/12/2021',
    claimant: 'Nguyễn Thanh Hà Linh',
    department: 'Operations',
    organization: 'AAV',
    type: 'Fund transfer request',
    claimedAmount: '25,000,000 VND',
    status: 'Inprogress',
  },
  {
    id: 5,
    name: 'Giải thưởng người truyền cảm hứng ActionAdi Việt Nam 2021',
    date: '28/12/2021',
    claimant: 'Hồ Thu Phương',
    department: 'Programme',
    organization: 'AAV',
    type: 'Expense claim',
    claimedAmount: '5,000,000 VND',
    status: 'Approved',
  },
  {
    id: 6,
    name: 'Thanh toán dịch vụ tư vấn cho Nguyễn Đức Hiếu',
    date: '28/12/2021',
    claimant: 'Lê Phương Thảo',
    department: 'Programme',
    organization: 'AAV',
    type: 'Fund transfer request',
    claimedAmount: '12,200,000 VND',
    status: 'Approved',
  },
]